# No real language, of course... Python is hopefully a lightweight runtime
# Update to trigger travis
language: python
env:
  global:
    - RS_ACCCOUNT=30601
    - RS_HOST=us-3.rightscale.com
    - secure: "JhSsjc+BeCkjzfrp/x5+Ew3eaQv1hPEBEdHZY8nevX/+RRh+xNdiqp0Er2QndKz6gGJR9pA0kZHanz9Fib2sztJaksIBlXWuWRbLvAMup4LpTXjW7od4FV1l/V2GJxKitSqSKuWCeP7q1W0Dp6RfmWXZd/YoA+zo6rdL91/GPmA="
install:
  - curl https://binaries.rightscale.com/rsbin/rsc/v6/rsc-linux-amd64.tgz | tar -zxf - -O rsc/rsc > rsc
  - chmod +x ./rsc
  - curl https://binaries.rightscale.com/rsbin/right_st/v1/right_st-linux-amd64.tgz | tar -zxf - -O right_st/right_st > rsc
  - chmod +x ./right_st
