language: python
env:
  global:
  - RS_ACCOUNT=30601
  - RS_HOST=us-3.rightscale.com
  - secure: Lvvt5zbNfQpdMnQugjU4V+w0TYN52T2y8+rLMmpRwQHXetwxmVaBUGPocSXRNm+VIskpAKm/vbcCI3ZwS4h2pIh/5ueWjYpWbc5bLtIKYRkX4RyWEKXp7970R/ZgZYxZ/rhtCHheE+U82JhRMHUKz3OhtVx6zVzuhns53TCURvCvpxVKN20KfLTohZqPsQiobBu+S8dM4xb+G9RM1NeD+yhLaywMXzTYwR/RUvDtk5rMcMnMBJ4I6+1f3gkuZc3/DuADBeVxpqQ4lLRzjfKwdrVIvTHjlL+70nccyNQzL4/w0eAoGpLCc17TxyqE3ru5kqveQz7S68eN6CmwNo9EXTjeEqCZkhzfRAlbTw9T66VolFb8dFz01h8tS+KE2qcg9PU3Uq79mWdubPAJUVd7eMNXkYYXNdtnTTXxFFO3UF76lh81sZGs3tSMD+O93SoQoaXcHLHo2ROKJuVSVI22vxKMCpnPYvl9S9kMxqq2n3U04vljN0pcNGiEgwajH5/Gdhk2eRcUbAB91LwqNaDGfuSrjdfirDnXgzyQe5ljxTgC13NMG86yOKtGBQIkb75wsgQwsjjseu+ZcYdjptgukCqysvu4KUU99OZxNttRPNollzkcBb9sfxDomqSxmQcFv4fWy7aZKAPC9BeWPtxDH4MOTTSyGl4ossgE+619b5Q=
install:
- curl https://binaries.rightscale.com/rsbin/rsc/v6/rsc-linux-amd64.tgz | tar -zxf
  - -O rsc/rsc > rsc
- chmod +x ./rsc
- curl https://binaries.rightscale.com/rsbin/right_st/v1/right_st-linux-amd64.tgz
  | tar -zxf - -O right_st/right_st > right_st
- chmod +x ./right_st
- chmod +x support_scripts/jenkinsBuildScript.sh
script: support_scripts/jenkinsBuildScript.sh
